name: Chrome checks
on:
  push:
    branches: [main]
  pull_request:
permissions:
  contents: read
jobs:
  chrome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803
        with:
          persist-credentials: false
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38
        with:
          node-version: "24"
      - run: npm install --global pnpm@10.32.1
      - run: pnpm install --frozen-lockfile
      - run: pnpm audit --prod --audit-level=high
      - run: pnpm run ci
